name: Build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v5
        with:
          submodules: "recursive"
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-disabled: true
          gradle-home-cache-cleanup: false

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: ""

      - name: Build with Gradle
        run: |
          ./gradlew zipRelease assembleRelease

      - name: Prepare artifact
        if: success()
        id: prepareArtifact
        run: |
          releaseName=`ls module/release/Nohello-v*-release.zip | awk -F '(/|.zip)' '{print $3}'` && echo "releaseName=$releaseName" >> $GITHUB_OUTPUT
          unzip module/release/Nohello-v*-release.zip -d module-release

      - name: Upload release
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.prepareArtifact.outputs.releaseName }}
          path: "./module-release/*"

      - name: Upload release mappings
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: release-mappings
          path: "./service/build/outputs/mapping/release"
          if-no-files-found: ignore
